/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeCompressCall */

#ifndef _Included_NativeCompressCall
#define _Included_NativeCompressCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeCompressCall
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeCompressCall_initFields
  (JNIEnv *, jclass);

/*
 * Class:     NativeCompressCall
 * Method:    end
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_NativeCompressCall_end
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     NativeCompressCall
 * Method:    reset
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_NativeCompressCall_reset
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     NativeCompressCall
 * Method:    init
 * Signature: (ZI)J
 */
JNIEXPORT jlong JNICALL Java_NativeCompressCall_init
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     NativeCompressCall
 * Method:    process
 * Signature: (JJIJIZ)I
 */
JNIEXPORT jint JNICALL Java_NativeCompressCall_process
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
